### ISSUE TITLE
用think run 内置跑不起来

### ISSUE THREAD

**Issue by liaoshengping** [rocky-git/ex-admin-thinkphp#1]
按照
composer create-project topthink/think 项目名称

配置数据库

composer require rockys/ex-admin-thinkphp

php think admin:install

![image.png](https://dd-static.jd.com/ddimg/jfs/t1/122167/32/30494/152707/6305c794E7370b69b/8af438fbbd14570d.png)

**Comment by chic900709** [comment]
用thinkphp内置的服务命令php think run 无法跑起来
用nginx 倒是可以

**Comment by rocky-git** [comment]
是的不支持内置
